complaint_registration_system/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    
    path('admin/', admin.site.urls),
     path('', include('complaints.urls')),

    
] 
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

complaints/urls.py
from django.urls import path
from complaints.views import About,Home,Contact,Logout_staff,Useri,regcomplaints,Viewstatcomplaints,Feedcomplaints,Staffdash,Viewcomplaints,Logout_user,Index,Addstaff,Adduser,Addservice
from .import views 



urlpatterns = [
    path('', Home, name='home'),
    path('about/', About, name='about'),
    path('contact/', Contact, name='contact'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('logout_admin/', views.logout_admin, name='logout_admin'),
    path('index/', Index, name='index'),
    path('adduser/', Adduser, name='adduser'),
    path('useri/', Useri, name='useri'),
    path('regcomplaints/', regcomplaints, name='regcomplaints'),
    path('viewstatcomplaints/', Viewstatcomplaints, name='viewstatcomplaints'),
    path('feedcomplaints/', Feedcomplaints, name='feedcomplaints'),
    path('staffdash/', Staffdash, name='staffdash'),
    path('staffi/', views.Staffi, name='staffi'),
    path('viewcomplaints/', Viewcomplaints, name='viewcomplaints'),
    path('user/signup/',views.SignupPage, name='signup'),
    path('user/logi/',views.LoginPage, name='logi'),
    path('logout_user/', Logout_user, name='logout_user'),
    path('logout_staff/', Logout_staff, name='logout_staff'),
    path('loggvt/', views.Login_govt, name='loggvt'),
    path('addstaff/', Addstaff, name='addstaff'),
    path('addservice/', Addservice, name='addservice'),
    path('adduser/', Adduser, name='adduser'),
    path('managestaff/', views.Managestaff, name='managestaff'),
    path('manageuser/', views.Manageuser, name='manageuser'),
    path('manageuseri/', views.Manageuseri, name='manageuseri'),
    path('viewcomp/', views.Viewcomp, name='viewcomp'),
    path('profile/', views.Profile, name='profile'),
    path('viewstatus/', views.viewstatus, name='viewstatuses'),
    path('adduseri/', views.Adduseri, name='adduseri'),
    path('viewcomplaints/', views.viewcomplaints, name='viewcomplaints'),
    path('viewplum/', views.viewplum, name='viewplum'),
    path('viewcon/', views.viewcon, name='viewcon'),
    path('viewother/', views.viewother, name='viewother'),
    path('con_staff/', views.con_staff, name='con_staff'),
    path('elec_staff/', views.elec_staff, name='elec_staff'),
    path('plum_staff/', views.plum_staff, name='plum_staff'),
    path('other_staff/', views.other_staff, name='other_staff'),
    path('con_delete_user<int:id>/', views.con_delete_user, name='con_delete_user'),
    path('plum_delete_user<int:id>/', views.plum_delete_user, name='plum_delete_user'),
    path('elec_delete_user<int:id>/', views.elec_delete_user, name='elec_delete_user'),
    path('other_delete_user<int:id>/', views.other_delete_user, name='other_delete_user'),
    #path('delete_user/<id>', views.delete_user, name='delete_user'),
    path('viewfeedback/', views.Viewfeedback, name='viewfeedback'),
    path('admin_delete_user/<int:id>',views.admin_delete_user,name='admin_delete_user'),
    path('staff_delete_user/<int:id>',views.staff_delete_user,name='staff_delete_user'),
    #path('send_email/', views.send_email, name='send_email'),
    path('contactus/', views.Contactus, name='contactus'),
    path('admin_update/<id>/',views.admin_update,name='admin_update'),
    path('admin_delete_comp/<id>/',views.admin_delete_comp,name='admin_delete_comp'),
    path('staff_update_comp/<id>/',views.staff_update_comp,name='staff_update_comp'),



]

complaints/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser


# Create your models here.
# class User(AbstractBaseUser):

#     is_admin=models.BooleanField('Is_admin',default=False)
#     is_member=models.BooleanField('Is_member',default=False)
#     is_staff=models.BooleanField('Is_staff',default=False)


class Regcomplaint(models.Model):
    #TYPE=(('Elecricity',"Elecricity"),('Plumbing & Drainage',"Plumbing & Drainage"),('Construction',"Construction"))
    name = models.CharField(max_length=15,null=True)
    flatblock=models.CharField(max_length=4,null=True)
    flatno=models.IntegerField(null=True)
    date =models.DateField()
    email=models.EmailField(null=True)
    phoneno=models.IntegerField(null=True)
    Electricity='Electricity'
    Plumbing='Plumbing'
    Construction='Construction'
    others='others'
    complainttype=models.CharField(choices=((Electricity,'Electricity'),(Plumbing,'Plumbing'),(Construction,'Construction'),(others,'others')),null=True,max_length=200)
    complainttitle =models.CharField(max_length=20)
    complaintmedia =models.ImageField(upload_to='images')
    complaintdescription =models.TextField(max_length=500)
    STATUS =(("Solved",'Solved'),("InProgress", 'InProgress'),("Pending",'Pending'))
    status=models.CharField(choices=STATUS,default="Pending",max_length=100)

class Feedback(models.Model):
    name = models.CharField(max_length=15,null=True)
    feed_sub=models.CharField(max_length=100) #feedback subject
    feed_description=models.TextField() #feedback description

    def __str__(self):
        return self.feed_sub
    

class Contactus(models.Model):
        name  = models.CharField(max_length=15,null=True)
        email=models.EmailField(max_length=100)
        message=models.TextField(max_length=100) 
        #feedback subject #feedback subject

        def __str__(self):
            return self.name
    

complaints/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User





# Create your forms here.



class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("first_name","last_name","username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
	







	

complaints/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages,auth
from .forms import NewUserForm #ServicesForm
#from .utils import send_email_to_client




from .models import *
# Create your views here.
def About(request):
    return render(request,'about.html')

def Home(request):
    return render(request,'home.html')


def Contact(request):
    return render(request,'contact.html')


def Useri(request):

    if 'username' in request.session:
        username = request.session['username']
        # Use the username as needed in your view logic
    # else:
    #     # Handle the case when the username is not in the session
    #     pass
    return render(request,'useri.html')

def regcomplaints(request):  # sourcery skip: extract-method
    username = request.session['username']
    
    if request.method == "POST":
        data = request.POST
        name=username
        flatblock=data.get('flatblock')
        flatno=data.get('flatno')
        date=data.get('date')
        email=data.get('email')
        phoneno=data.get('phoneno')
        complainttype=data.get('complainttype')
        complainttitle=data.get('complainttitle')
        complaintdescription=data.get('complaintdescription')
        complaintmedia=request.FILES.get('complaintmedia')
        
        Regcomplaint.objects.create(
            
            name=name,
            flatblock=flatblock,
            flatno=flatno,
            date=date,
            email=email,
            phoneno=phoneno,
            complainttype=complainttype,
            complainttitle=complainttitle,
            complaintdescription=complaintdescription,
            complaintmedia=complaintmedia,
        )
        return redirect('/regcomplaints/')
    queryset =Regcomplaint.objects.all()
    context ={
        'regcomplaints':queryset,
         
        }  
    
    return render(request,'regcomplaints.html',context)

def Viewstatcomplaints(request):
    username=request.session['username']
    queryset =Regcomplaint.objects.filter(name= username)
    context ={'regcomplaints':queryset}  
    
    return render(request,'viewstatcomplaints.html',context)

def Feedcomplaints(request):
    username = request.session['username']
    if request.method == "POST":
        name = username
        feed_sub = request.POST['feed_sub']
        feed_description = request.POST['feed_description']
        Feedback.objects.create(name=name,feed_sub=feed_sub,
                                     feed_description=feed_description, 
                                    )  
        Feedback(name=name,feed_sub=feed_sub, feed_description=feed_description)
        messages.info(request,'Successfully Added your Feedback')
        return redirect('feedcomplaints')
    return render(request,'feedcomplaints.html')

def Staffdash(request):
    return render(request,'staffdash.html')
def Viewcomplaints(request):
    return render(request,'viewcomplaints.html')  

def Index(request):
    if not request.user.is_staff:
        return redirect('login')
    return render(request,'index.html')

def Adduser(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"signup Successfull.")
            return redirect('adduser')
        else:
            messages.error(request,"unsuccessfull registration.invalid information")
    form = NewUserForm()
    return render(request=request, template_name="admin/adduser.html", context={"register_form":form})
        
   
        
    

def admin_login(request):
    error = ""
    if request.method == "POST":
        u =request.POST['uname']
        p =request.POST['pwd']
        user =auth.authenticate(username=u, password=p)
        try  :
            if user.is_superuser:
                login(request,user)
                error ="no"
            else:
                error="yes"
        except Exception:
            error="yes"
    d={'error':error}
    return render(request,'login.html',d)

def logout_admin(request):
    logout(request)
    return redirect('admin_login')

# def logout_admin(request):
    
#     logout(request)
#     return redirect('Login')




#user reg
def SignupPage(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"signup Successfull.")
            return redirect('logi')
    messages.error(request,"unsuccessfull registration.invalid information")
    form = NewUserForm()
    return render(request=request, template_name="user/signup.html", context={"register_form":form})
        
	
    #if request.method == "POST":
#        uname=request.POST.get('username')
#        email=request.POST.get('email')
#        pass1=request.POST.get('password1')
#        pass2=request.POST.get('password2')
#        if pass1!=pass2:
#            return HttpResponse("your password and confirm pass are not same.")
    #    my_user=User.objects.create_user(uname,email,pass1)
    #   my_user.save()
    #    return redirect('logi')
    
#    return render(request,'user/signup.html')



        
#staff login
def Login_govt(request):
    # sourcery skip: remove-unnecessary-else, swap-if-else-branches
    error=""
    if request.method == "POST":
        username=request.POST.get('uname')
        pass1=request.POST.get('pwd')
        user=authenticate(request, username=username, password=pass1)
        
        try  :
            if user.is_staff and not user.is_superuser:
                login(request,user)
                request.session['username'] = user.username
                error ="no"
            else:
                error="yes"
        except Exception:
            error="yes"
    d={'error':error}
    return render(request,'loggvt.html',d)   

def Logout_staff(request):
    if not request.user.is_staff:
        return redirect('loggvt')
    logout(request)
    return redirect('loggvt')




def LoginPage(request):  
     
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['username'] = user.username
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("useri")
            else:
                messages.error(request,"Invalid username or password.")
    else:
                messages.error(request,"Invalid username or password.")
                form = AuthenticationForm()
    return render(request=request, template_name="user/logi.html", context={"login_form":form})
   


def Logout_user(request):
    if request.user is not None:
        return redirect('logi')
    logout(request)
    return redirect('logi')





#admin side

def Addservice(request):
    return render(request,'admin/addservice.html')

def Addstaff(request):
    return render(request,'admin/addstaff.html')

def Managestaff(request):
    return render(request,'admin/managestaff.html')

def Manageuser(request):
    #username=request.session['username']
    
    queryset =User.objects.all()
    context ={'Adduser':queryset}  
    return render(request, 'admin/manageuser.html',context)

def Viewcomp(request):
    queryset =Regcomplaint.objects.all()
    context ={'regcomplaints':queryset}  
    return render(request,'admin/viewcomp.html',context)

def viewstatus(request):
    queryset =Regcomplaint.objects.all()
    context ={'regcomplaints':queryset}  
    return render(request,'admin/viewstatus.html',context)

def Viewfeedback(request):
    queryset=Feedback.objects.all()
    context={'Feedcomplaints':queryset}
    return render(request,'admin/viewfeedback.html',context)


#staff side
def Staffi(request):
    return render(request,'staff/staffi.html')

def Adduseri(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"signup Successfull.")
            return redirect('adduseri')
    messages.error(request,"unsuccessfull registration.invalid information")
    form = NewUserForm()
    return render(request=request, template_name="staff/adduseri.html", context={"register_form":form})

def Manageuseri(request):
    queryset =User.objects.all()
    context ={'Adduser':queryset}  
    return render(request,'staff/manageuseri.html', context)

def viewcomplaints(request):
    #complainttype = request.session('complainttype')
    # if complainttype == 'Electricity':
    #     queryset = Regcomplaint.objects.filter(complainttype='Electricity')
    #     context = {'viewcomplaints': queryset}
    #     templates = 'staff/viewcomplaints.html'
    # elif complainttype == 'Plumbing':
    #     queryset = Regcomplaint.objects.filter(complainttype='Plumbing')
    #     context = {'viewplum': queryset}
    #     templates = 'staff/viewplum.html'
    # elif complainttype == 'Construction':
    #     queryset = Regcomplaint.objects.filter(complainttype='Construction')
    #     context = {'viewcon': queryset}
    #     templates = 'staff/viewcon.html'
    # else:
    #     queryset = Regcomplaint.objects.filter(complainttype='others')
    #     context = {'viewother': queryset}
    #     templates = 'staff/viewother.html'

    # return render(request, templates, context)

complaints/templates/user/feedcomplaints.html
{% include 'base.html' %}

{% include 'nav.html' %}
{% include 'usersidebar.html' %}
{% block content %}
<div class="glass-container mt-5 mb-1" ><br><br><br>
  <form class="glass-form col-6 mx-auto  p-3" method="post" enctype="multipart/form-data">
      <!-- {% csrf_token %}
    <h1 class="text-center">Please Submit Your Feedback</h1>
    <input type="text"  placeholder="Enter Complaint Subject" name="feed_sub">
    <input type="text" placeholder="Enter your Feedback" name="feed_description"> -->
    <!-- <div class="container mt-5 mb-1">
      <form class="col-6 mx-auto card p-3" method="post" enctype="multipart/form-data"> -->
      {% csrf_token %}
          <h1 class="text-center">Feedback</h1>
          <hr>
           <div class="mb-3">
              <label for="exampleInputName" class="form-label">Complaint Subject</label>
              <input name="feed_sub" required type="text" placeholder="Enter Complaint Subject" class="form-control" id="exampleInputName">
            </div> 
            <div class="mb-3">
              <label for="exampleInputName" class="form-label">Feedback</label>
              <input name="feed_description" required type="text" placeholder="Enter your Feedback" class="form-control" id="exampleInputName">
            </div> 
    <button type="submit" class="form-control btn btn-primary">Submit</button>
  </form>
  <!-- {%for msg in messages%}
  <h3>{{msg}}</h3>
  {%endfor%} -->
</div>

<!-- <style>

  * {
    box-sizing: border-box;
    font-family: 'Poppins',sans-serif;
  
  }
  .glass-container {
    position: relative;
    height: 1000px;
    width: 750px;
    margin: 0 auto;
    margin-top: 0px;
  }
  .glass-form {
    color: #0f0f0f;
    padding: 20px;
    height: auto;
    margin: 0 auto;
    background: rgba(0, 0, 0, 0.6);
    border-radius: 10px;
    border-top: 1px solid rgba(0, 0, 0, 0.4);
    border-left: 1px solid rgba(0, 0, 0, 0.2);
    border-right: thin solid rgba(0, 0, 0, 0.3);
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(12px);
    box-shadow: 0px 28px 48px rgba(0, 0, 0, 0.1);
    place-content: center;
  }
  .form-footer {
    text-align: center;
  }
  .glass-form a {
    font-size: 12px;
    text-decoration: underline;
    color: #fff8f8;
  }
  .glass-form  input {
    display: block;
    color: #000000;
    width: 100%;
    height: 65px;
    margin: 0 auto;
    margin-bottom: 30px;
    padding: 10px;
    outline: none;
    background: rgba(225, 225, 225, 0.1);
    border: none;
    border-top: 1px solid rgba(225, 225, 225, 0.3);
    box-shadow: 0px 10px 21px rgba(0, 0, 0, 0.1);
  
  }
  .glass-form input:hover {
    background: rgb(218, 218, 218);
    transition: 0.5s;
  }
  input::placeholder {
    color: #ede7e7;
  }
  
  </style> -->
  
{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/user/logi.html
    {% include 'base.html' %}
    {% include 'navigation.html' %}
    {% load crispy_forms_tags %}

    {% block content %}
    
    
    <form method="POST">
    <div class="container w-50 my-5">
        <h1 class="text-center">Resident Login</h1>
        
            {% csrf_token %}
            {{ login_form|crispy }}      
          <br>
          <button class="form-control btn btn-primary" type="submit">Login</button>
    </form>
        <p class="text-center">Don't have an account? <a href="{% url 'signup' %}">Create an account</a>.</p>
        <p class="text-center"><a href="">Forgot password?</a></p>
      </div>
      
          
   <!-- <form method="post">
        <div class="container w-50 my-5">
            <h2 class="text-center">Member LOGIN</h2>
            <form method="POST">
                {% csrf_token %}
                <label>Member Name</label>
                <input type="text" class="form-control" name="uname">
                <label>Password</label>
                <input type="password" class="form-control" name="pwd">
                <br>
                <input type="submit" value="login" class="form-control btn btn-primary ">
                <a href="{% url 'signup' %}" >Create a account</a>
            </form>
            
        </div>

        
         <input type="button" value=""> -->
        <!-- <div class="social">
          <div class="go"><i class="fab fa-google"></i>  Google</div>
          <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div> 
       
    </form>-->
   

{% endblock %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/user/nav.html
<style>
  .navbar{
    position: relative;
  }
</style>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><h1>RESIDENTS ASSOCIATION <br>COMPLAINT REGISTRATION SYSTEM</h1></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'useri' %}">Back to User DashBoard</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Services
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'regcomplaints' %}">register complaints</a></li>
              <li><a class="dropdown-item" href="{% url 'viewstatcomplaints' %}">view complaint status</a></li>
              <li><a class="dropdown-item" href="{% url 'feedcomplaints' %}">feeback</a></li>
              </ul>
              
            </li>
            {% if request.user is not None %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout_user' %}">Logout</a>
            </li>
            {% endif %}      
            
         
              
          </ul>
        </div>      
          
    </div>
  </nav>

complaints/templates/user/password_reset.html
{% include 'base.html' %}

{% include 'nav.html' %} 
{% include 'usersidebar.html' %}
{% load crispy_forms_tags %}
{% block content %}
	
{% endblock %}

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>    
{% include 'footer.html' %}

complaints/templates/user/profile.html
{% include 'base.html' %}
{% include 'nav.html' %}

{%block body %}

{% if user.is_authenticated %}
<div class="container">
<div class="container-xl px-4 ">
    <!-- Account page navigation-->
   
    <hr class="">
    <div class="row">
        
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card">
                <div class="card-header">My Profile</div>
                <div class="card-body">
                    
                       
                        <div class="mb-3">
                            <label class="small mb-1" for="inputUsername">Username (how your name will appear to other users on the site)</label>
                            <input class="form-control" id="inputUsername" type="text" placeholder="{{user.username}}" value="{{user.username}}" disabled>
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (first name)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputFirstName">First name</label>
                                <input class="form-control" id="inputFirstName" type="text" placeholder="{{user.first_name}}" value="{{user.first_name}}" disabled>
                            </div>
                            <!-- Form Group (last name)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputLastName">Last name</label>
                                <input class="form-control" id="inputLastName" type="text" placeholder="{{user.last_name}}" value="{{user.last_name}}" disabled>
                            </div>
                        </div>
                        <!-- Form Row        -->
                        
                            <!-- Form Group (location)-->
                           
                       
                        <!-- Form Group (email address)-->
                        <div class="mb-3">
                            <label class="small mb-1" for="inputEmailAddress">Email address</label>
                            <input class="form-control" id="inputEmailAddress" type="email" placeholder="{{user.email}}" value="{{user.email}}" disabled>
                        </div>
                        <!-- Form Row-->
                  
                            <!-- Form Group (birthday)-->
                            
                        </div>
                    </div>
                        <!-- Save changes button-->
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endif %}


<style>




.card {
    box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
}
.card .card-header {
    font-weight: 500;
}
.card-header:first-child {
    border-radius: 0.35rem 0.35rem 0 0;
}
.card-header {
    /* padding: 0% 22rem; */
    text-align: center;
    margin-bottom: 0;
    background-color: rgba(33, 40, 50, 0.03);
    /* border-bottom: 1px solid rgba(33, 40, 50, 0.125); */
}
.form-control, .dataTable-input {
    display: block;
    width: 100%;
    padding: 0.875rem 1.125rem;
    font-size: 0.875rem;
    font-weight: 400;
    /* line-height: 1; */
    color: #69707a;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #c5ccd6;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.35rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

.nav-borders .nav-link.active {
    color: #0061f2;
    border-bottom-color: #0061f2;
}
.nav-borders .nav-link {
    color: #69707a;
    border-bottom-width: 0.125rem;
    border-bottom-style: solid;
    border-bottom-color: transparent;
    /* padding-top: 0.5rem; */
    /* padding-bottom: 0.5rem; */
    padding-left: 0;
    padding-right: 0;
    /* margin-left: 1rem; */
    /* margin-right: 1rem; */
}

</style>

{%endblock%}<br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/user/regcomplaints.html
{% include 'base.html' %}
{% include 'nav.html' %}
{% include 'usersidebar.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1 class="text-center"> Complaint Registration Form</h1>
  
  <div class="container mt-5 mb-1">
    <form class="col-6 mx-auto card p-3" method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <h1 class="text-center"> Register Your Complaints</h1>
        <hr>
        {% comment %} <div class="mb-3">
            <label for="exampleInputName" class="form-label">Name</label>
            <input name="name" required type="text" class="form-control" id="exampleInputName">
          </div> {% endcomment %}
          {% comment %} <div class="mb-3">
            <label for="cars">Section</label>

            
            <select name="cars" class="form-control" id="cars" >
            {% for items in sections %}
                <option value="sections">{{items.sections}}</option>
            {% endfor %}    
            </select>
          </div> {% endcomment %}
          <div class="mb-3">
            <label for="exampleInputflatblock" class="form-label">Flat Block</label>
            <input name="flatblock" required type="text" class="form-control" id="exampleInputflatblock">
          </div>
          <div class="mb-3">
            <label for="exampleInputflatno" class="form-label">Flat Number</label>
            <input name="flatno" required type="number" class="form-control" id="exampleInputflatno">
          </div>
          <div class="mb-3">
            <label for="exampleInputdate" class="form-label">Date</label>
            <input name="date" required type="date" class="form-control" id="exampleInputdate">
          </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input name="email" required  type="email" class="form-control"  aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputphoneno" class="form-label">Phone Numer</label>
          <input name="phoneno" required  type="number" class="form-control" >
        </div>
        <div class="mb-3">
          <label for="exampleInputphoneno" class="form-label">Complaint Type</label>
          <select class="form-control" name="complainttype" required="" id="id_complainttype">
            <option value="" selected=""></option>
          
            <option value="Electricity">Electricity</option>
          
            <option value="Plumbing">Plumbing</option>
          
            <option value="Construction">Construction</option>
            <option value="others">others</option>
          
          </select>
        </div>
        <div class="mb-3">
          <label for="exampleInputdate" class="form-label">Complaint Subject</label>
          <input name="complainttitle" required type="text" class="form-control" id="exampleInputdate">
        </div>
        
        <div class="mb-3">
            <label for="exampleInputfiles" class="form-label">Files</label>
            <input name="complaintmedia" type="file" class="form-control" id="exampleInputfiles">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Complaint Description</label>
            <textarea class="form-control" name="complaintdescription" required id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>
        <button type="submit" class="btn btn-primary" >Submit your Complaints</button>

        <!-- <a href="" type="submit" class="btn btn-primary">submit</a> -->
    </form>

      
         
  </div>
{% endblock content %}
{% include 'footer.html' %}