complaint_registration_system/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    
    path('admin/', admin.site.urls),
     path('', include('complaints.urls')),

    
] 
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

complaints/urls.py
from django.urls import path
from complaints.views import About,Home,Contact,Logout_staff,Useri,regcomplaints,Viewstatcomplaints,Feedcomplaints,Staffdash,Viewcomplaints,Logout_user,Index,Addstaff,Adduser,Addservice
from .import views 



urlpatterns = [
    path('', Home, name='home'),
    path('about/', About, name='about'),
    path('contact/', Contact, name='contact'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('logout_admin/', views.logout_admin, name='logout_admin'),
    path('index/', Index, name='index'),
    path('adduser/', Adduser, name='adduser'),
    path('useri/', Useri, name='useri'),
    path('regcomplaints/', regcomplaints, name='regcomplaints'),
    path('viewstatcomplaints/', Viewstatcomplaints, name='viewstatcomplaints'),
    path('feedcomplaints/', Feedcomplaints, name='feedcomplaints'),
    path('staffdash/', Staffdash, name='staffdash'),
    path('staffi/', views.Staffi, name='staffi'),
    path('viewcomplaints/', Viewcomplaints, name='viewcomplaints'),
    path('user/signup/',views.SignupPage, name='signup'),
    path('user/logi/',views.LoginPage, name='logi'),
    path('logout_user/', Logout_user, name='logout_user'),
    path('logout_staff/', Logout_staff, name='logout_staff'),
    path('loggvt/', views.Login_govt, name='loggvt'),
    path('addstaff/', Addstaff, name='addstaff'),
    path('addservice/', Addservice, name='addservice'),
    path('adduser/', Adduser, name='adduser'),
    path('managestaff/', views.Managestaff, name='managestaff'),
    path('manageuser/', views.Manageuser, name='manageuser'),
    path('manageuseri/', views.Manageuseri, name='manageuseri'),
    path('viewcomp/', views.Viewcomp, name='viewcomp'),
    path('profile/', views.Profile, name='profile'),
    path('viewstatus/', views.viewstatus, name='viewstatuses'),
    path('adduseri/', views.Adduseri, name='adduseri'),
    path('viewcomplaints/', views.viewcomplaints, name='viewcomplaints'),
    path('viewplum/', views.viewplum, name='viewplum'),
    path('viewcon/', views.viewcon, name='viewcon'),
    path('viewother/', views.viewother, name='viewother'),
    path('con_staff/', views.con_staff, name='con_staff'),
    path('elec_staff/', views.elec_staff, name='elec_staff'),
    path('plum_staff/', views.plum_staff, name='plum_staff'),
    path('other_staff/', views.other_staff, name='other_staff'),
    path('con_delete_user<int:id>/', views.con_delete_user, name='con_delete_user'),
    path('plum_delete_user<int:id>/', views.plum_delete_user, name='plum_delete_user'),
    path('elec_delete_user<int:id>/', views.elec_delete_user, name='elec_delete_user'),
    path('other_delete_user<int:id>/', views.other_delete_user, name='other_delete_user'),
    #path('delete_user/<id>', views.delete_user, name='delete_user'),
    path('viewfeedback/', views.Viewfeedback, name='viewfeedback'),
    path('admin_delete_user/<int:id>',views.admin_delete_user,name='admin_delete_user'),
    path('staff_delete_user/<int:id>',views.staff_delete_user,name='staff_delete_user'),
    #path('send_email/', views.send_email, name='send_email'),
    path('contactus/', views.Contactus, name='contactus'),
    path('admin_update/<id>/',views.admin_update,name='admin_update'),
    path('admin_delete_comp/<id>/',views.admin_delete_comp,name='admin_delete_comp'),
    path('staff_update_comp/<id>/',views.staff_update_comp,name='staff_update_comp'),



]

complaints/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser


# Create your models here.
# class User(AbstractBaseUser):

#     is_admin=models.BooleanField('Is_admin',default=False)
#     is_member=models.BooleanField('Is_member',default=False)
#     is_staff=models.BooleanField('Is_staff',default=False)


class Regcomplaint(models.Model):
    #TYPE=(('Elecricity',"Elecricity"),('Plumbing & Drainage',"Plumbing & Drainage"),('Construction',"Construction"))
    name = models.CharField(max_length=15,null=True)
    flatblock=models.CharField(max_length=4,null=True)
    flatno=models.IntegerField(null=True)
    date =models.DateField()
    email=models.EmailField(null=True)
    phoneno=models.IntegerField(null=True)
    Electricity='Electricity'
    Plumbing='Plumbing'
    Construction='Construction'
    others='others'
    complainttype=models.CharField(choices=((Electricity,'Electricity'),(Plumbing,'Plumbing'),(Construction,'Construction'),(others,'others')),null=True,max_length=200)
    complainttitle =models.CharField(max_length=20)
    complaintmedia =models.ImageField(upload_to='images')
    complaintdescription =models.TextField(max_length=500)
    STATUS =(("Solved",'Solved'),("InProgress", 'InProgress'),("Pending",'Pending'))
    status=models.CharField(choices=STATUS,default="Pending",max_length=100)

class Feedback(models.Model):
    name = models.CharField(max_length=15,null=True)
    feed_sub=models.CharField(max_length=100) #feedback subject
    feed_description=models.TextField() #feedback description

    def __str__(self):
        return self.feed_sub
    

class Contactus(models.Model):
        name  = models.CharField(max_length=15,null=True)
        email=models.EmailField(max_length=100)
        message=models.TextField(max_length=100) 
        #feedback subject #feedback subject

        def __str__(self):
            return self.name
    

complaints/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User





# Create your forms here.



class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("first_name","last_name","username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
	







	

complaints/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages,auth
from .forms import NewUserForm #ServicesForm
#from .utils import send_email_to_client




from .models import *
# Create your views here.
def About(request):
    return render(request,'about.html')

def Home(request):
    return render(request,'home.html')


def Contact(request):
    return render(request,'contact.html')


def Useri(request):

    if 'username' in request.session:
        username = request.session['username']
        # Use the username as needed in your view logic
    # else:
    #     # Handle the case when the username is not in the session
    #     pass
    return render(request,'useri.html')

def regcomplaints(request):  # sourcery skip: extract-method
    username = request.session['username']
    
    if request.method == "POST":
        data = request.POST
        name=username
        flatblock=data.get('flatblock')
        flatno=data.get('flatno')
        date=data.get('date')
        email=data.get('email')
        phoneno=data.get('phoneno')
        complainttype=data.get('complainttype')
        complainttitle=data.get('complainttitle')
        complaintdescription=data.get('complaintdescription')
        complaintmedia=request.FILES.get('complaintmedia')
        
        Regcomplaint.objects.create(
            
            name=name,
            flatblock=flatblock,
            flatno=flatno,
            date=date,
            email=email,
            phoneno=phoneno,
            complainttype=complainttype,
            complainttitle=complainttitle,
            complaintdescription=complaintdescription,
            complaintmedia=complaintmedia,
        )
        return redirect('/regcomplaints/')
    queryset =Regcomplaint.objects.all()
    context ={
        'regcomplaints':queryset,
         
        }  
    
    return render(request,'regcomplaints.html',context)

def Viewstatcomplaints(request):
    username=request.session['username']
    queryset =Regcomplaint.objects.filter(name= username)
    context ={'regcomplaints':queryset}  
    
    return render(request,'viewstatcomplaints.html',context)

def Feedcomplaints(request):
    username = request.session['username']
    if request.method == "POST":
        name = username
        feed_sub = request.POST['feed_sub']
        feed_description = request.POST['feed_description']
        Feedback.objects.create(name=name,feed_sub=feed_sub,
                                     feed_description=feed_description, 
                                    )  
        Feedback(name=name,feed_sub=feed_sub, feed_description=feed_description)
        messages.info(request,'Successfully Added your Feedback')
        return redirect('feedcomplaints')
    return render(request,'feedcomplaints.html')

def Staffdash(request):
    return render(request,'staffdash.html')
def Viewcomplaints(request):
    return render(request,'viewcomplaints.html')  

def Index(request):
    if not request.user.is_staff:
        return redirect('login')
    return render(request,'index.html')

def Adduser(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"signup Successfull.")
            return redirect('adduser')
        else:
            messages.error(request,"unsuccessfull registration.invalid information")
    form = NewUserForm()
    return render(request=request, template_name="admin/adduser.html", context={"register_form":form})
        
   
        
    

def admin_login(request):
    error = ""
    if request.method == "POST":
        u =request.POST['uname']
        p =request.POST['pwd']
        user =auth.authenticate(username=u, password=p)
        try  :
            if user.is_superuser:
                login(request,user)
                error ="no"
            else:
                error="yes"
        except Exception:
            error="yes"
    d={'error':error}
    return render(request,'login.html',d)

def logout_admin(request):
    logout(request)
    return redirect('admin_login')

# def logout_admin(request):
    
#     logout(request)
#     return redirect('Login')




#user reg
def SignupPage(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"signup Successfull.")
            return redirect('logi')
    messages.error(request,"unsuccessfull registration.invalid information")
    form = NewUserForm()
    return render(request=request, template_name="user/signup.html", context={"register_form":form})
        
	
    #if request.method == "POST":
#        uname=request.POST.get('username')
#        email=request.POST.get('email')
#        pass1=request.POST.get('password1')
#        pass2=request.POST.get('password2')
#        if pass1!=pass2:
#            return HttpResponse("your password and confirm pass are not same.")
    #    my_user=User.objects.create_user(uname,email,pass1)
    #   my_user.save()
    #    return redirect('logi')
    
#    return render(request,'user/signup.html')



        
#staff login
def Login_govt(request):
    # sourcery skip: remove-unnecessary-else, swap-if-else-branches
    error=""
    if request.method == "POST":
        username=request.POST.get('uname')
        pass1=request.POST.get('pwd')
        user=authenticate(request, username=username, password=pass1)
        
        try  :
            if user.is_staff and not user.is_superuser:
                login(request,user)
                request.session['username'] = user.username
                error ="no"
            else:
                error="yes"
        except Exception:
            error="yes"
    d={'error':error}
    return render(request,'loggvt.html',d)   

def Logout_staff(request):
    if not request.user.is_staff:
        return redirect('loggvt')
    logout(request)
    return redirect('loggvt')




def LoginPage(request):  
     
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['username'] = user.username
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("useri")
            else:
                messages.error(request,"Invalid username or password.")
    else:
                messages.error(request,"Invalid username or password.")
                form = AuthenticationForm()
    return render(request=request, template_name="user/logi.html", context={"login_form":form})
   


def Logout_user(request):
    if request.user is not None:
        return redirect('logi')
    logout(request)
    return redirect('logi')





#admin side

def Addservice(request):
    return render(request,'admin/addservice.html')

def Addstaff(request):
    return render(request,'admin/addstaff.html')

def Managestaff(request):
    return render(request,'admin/managestaff.html')

def Manageuser(request):
    #username=request.session['username']
    
    queryset =User.objects.all()
    context ={'Adduser':queryset}  
    return render(request, 'admin/manageuser.html',context)

def Viewcomp(request):
    queryset =Regcomplaint.objects.all()
    context ={'regcomplaints':queryset}  
    return render(request,'admin/viewcomp.html',context)

def viewstatus(request):
    queryset =Regcomplaint.objects.all()
    context ={'regcomplaints':queryset}  
    return render(request,'admin/viewstatus.html',context)

def Viewfeedback(request):
    queryset=Feedback.objects.all()
    context={'Feedcomplaints':queryset}
    return render(request,'admin/viewfeedback.html',context)


#staff side
def Staffi(request):
    return render(request,'staff/staffi.html')

def Adduseri(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            messages.success(request,"signup Successfull.")
            return redirect('adduseri')
    messages.error(request,"unsuccessfull registration.invalid information")
    form = NewUserForm()
    return render(request=request, template_name="staff/adduseri.html", context={"register_form":form})

def Manageuseri(request):
    queryset =User.objects.all()
    context ={'Adduser':queryset}  
    return render(request,'staff/manageuseri.html', context)

def viewcomplaints(request):
    #complainttype = request.session('complainttype')
    # if complainttype == 'Electricity':
    #     queryset = Regcomplaint.objects.filter(complainttype='Electricity')
    #     context = {'viewcomplaints': queryset}
    #     templates = 'staff/viewcomplaints.html'
    # elif complainttype == 'Plumbing':
    #     queryset = Regcomplaint.objects.filter(complainttype='Plumbing')
    #     context = {'viewplum': queryset}
    #     templates = 'staff/viewplum.html'
    # elif complainttype == 'Construction':
    #     queryset = Regcomplaint.objects.filter(complainttype='Construction')
    #     context = {'viewcon': queryset}
    #     templates = 'staff/viewcon.html'
    # else:
    #     queryset = Regcomplaint.objects.filter(complainttype='others')
    #     context = {'viewother': queryset}
    #     templates = 'staff/viewother.html'

    # return render(request, templates, context)

complaints/templates/staff/con_delete_user.html
{% include 'base.html' %}
{% include 'navb.html' %}
{% include 'staffdash.html' %} 
{% block content %}
<div class="container mt-5">
<div class="center mt-10">
<form method="post">
    {%csrf_token%}
    <h5>Are you sure to delete this person?</h5><br>
      <input class="btn btn-warning" type="submit">
  </form>
</div>
{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

<style>

.container{
  text-align: center;
}
</style>

complaints/templates/staff/con_staff.html
{% include 'base.html' %}

{% include 'navb.html' %} 
{% include 'staffdash.html' %}
{% block content %}
<div class="container w-50 my-5">
 
</div>
<h1 class="text-center"> LOGIN DETAILS</h1>

<div style="padding-left: 173px;" class="container mt-5 ">
    
{% if viewcon %} 
    <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last name</th>
            <th scope="col">User name</th>
            <th scope="col">Email address</th>
            
            <th scope="col">Actions</th>
            
            
          </tr>
        </thead>
        <tbody>
          
          {% for adduser in viewcon %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{adduser.name}}</td>
            <td>{{adduser.email}}</td>
            <td>{{adduser.complainttype}}</td>
            <!-- <td><a class="btn btn-danger" href="{%url 'admin_delete_user' user.id %}">Delete</a></td> -->
            <td><a class="btn btn-danger" href="{%url 'con_delete_user' adduser.id %}">Delete</a></td>

            <!-- <td> <button href="/delete_user/{{adduser.id}}" class="btn btn-danger">Delete</button></td>
               -->
          </tr>
          
          {% endfor %}
          
        </tbody>
      </table>

{% endif %}
</div>


{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>    <br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/staff/elec_staff.html
{% include 'base.html' %}

{% include 'navb.html' %} 
{% include 'staffdash.html' %}
{% block content %}
<div class="container w-50 my-5">
 
</div>
<h1 class="text-center"> LOGIN DETAILS</h1>

<div style="padding-left: 173px;" class="container mt-5 ">
    
{% if viewelec %} 
    <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last name</th>
            <th scope="col">User name</th>
            <th scope="col">Email address</th>
            
            <th scope="col">Actions</th>
            
            
          </tr>
        </thead>
        <tbody>
          
          {% for adduser in viewelec %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{adduser.name}}</td>
            <td>{{adduser.email}}</td>
            <td>{{adduser.complainttype}}</td>
            <!-- <td><a class="btn btn-danger" href="{%url 'admin_delete_user' user.id %}">Delete</a></td> -->
            <td><a class="btn btn-danger" href="{%url 'elec_delete_user' adduser.id %}">Delete</a></td>

            <!-- <td> <button href="/delete_user/{{adduser.id}}" class="btn btn-danger">Delete</button></td>
               -->
          </tr>
          
          {% endfor %}
          
        </tbody>
      </table>

{% endif %}
</div>


{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>    <br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/staff/loggvt.html
{% include 'base.html' %}

{% include 'navigation.html' %} 

{% block content %}

          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'admin_login' %}">Admin</a></li>
            <li><a class="dropdown-item" href="{% url 'loggvt' %}">Resident staff</a></li>
            <li><a class="dropdown-item" href="{% url 'logi' %}">Member</a></li>
            </ul>
          </li>
         
              
          </ul>
        </div>      
          
    </div>
  </nav>
  {% if error == "no" %}
  <script>
      alert('logged in successfully');
      window.location = "{% url 'staffi' %}";
  </script>
{% endif %}
{% if error == "yes" %}
  <script>
  alert('invalid login try again!');
  </script>
{% endif %}

<div class="container w-50 my-5">
    <h2 class="text-center">Resident staff Login</h2>
    <form method="POST">
        {% csrf_token %}
        <label>Resident staff</label>
        <input type="text" class="form-control" name="uname">
        <label>Password</label>
        <input type="password" class="form-control" name="pwd">
        <br>
        <input type="submit" value="login" class="form-control btn btn-primary">
        <a href="{% url 'signup' %}" >Create a account</a>
    </form>
</div>

{% endblock content %}


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/staff/navb.html
{% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"> {% endcomment %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container ">
        <a class="navbar-brand" href="#"><h1>RESIDENTS ASSOCIATION <br>COMPLAINT REGISTRATION SYSTEM</h1></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href=""></a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'staffi' %}">Back to staff DashBoard</a>
            </li>
            

            {% if request.user is not None %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout_staff' %}">Logout</a>
            </li>
              {% endif %}      
            
         
              
          </ul>
        </div>      
          
    </div>
  </nav>

complaints/templates/staff/other_delete_user.html
{% include 'base.html' %}
{% include 'navb.html' %}
{% include 'staffdash.html' %} 
{% block content %}
<div class="container mt-5">
<div class="center mt-10">
<form method="post">
    {%csrf_token%}
    <h5>Are you sure to delete this person?</h5><br>
      <input class="btn btn-warning" type="submit">
  </form>
</div>
{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

<style>

.container{
  text-align: center;
}
</style>

complaints/templates/staff/plum_delete_user.html
{% include 'base.html' %}
{% include 'navb.html' %}
{% include 'staffdash.html' %} 
{% block content %}
<div class="container mt-5">
<div class="center mt-10">
<form method="post">
    {%csrf_token%}
    <h5>Are you sure to delete this person?</h5><br>
      <input class="btn btn-warning" type="submit">
  </form>
</div>
{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

<style>

.container{
  text-align: center;
}
</style>

complaints/templates/staff/plum_staff.html
{% include 'base.html' %}

{% include 'navb.html' %} 
{% include 'staffdash.html' %}
{% block content %}
<div class="container w-50 my-5">
 
</div>
<h1 class="text-center"> LOGIN DETAILS</h1>

<div style="padding-left: 173px;" class="container mt-5 ">
    
{% if viewplum %} 
    <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">User name</th>
            <th scope="col">Email address</th>
            <th scope="col">Complaint Type</th>
            <th scope="col">Actions</th>
            
            
            
            
          </tr>
        </thead>
        <tbody>
          
          {% for adduser in viewplum %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{adduser.name}}</td>
            <td>{{adduser.email}}</td>
            <td>{{adduser.complainttype}}</td>
            <!-- <td><a class="btn btn-danger" href="{%url 'admin_delete_user' user.id %}">Delete</a></td> -->
            <td><a class="btn btn-danger" href="{%url 'plum_delete_user' adduser.id %}">Delete</a></td>

            <!-- <td> <button href="/delete_user/{{adduser.id}}" class="btn btn-danger">Delete</button></td>
               -->
          </tr>
          
          {% endfor %}
          
        </tbody>
      </table>

{% endif %}
</div>


{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>    <br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

complaints/templates/staff/staff_update_comp.html
{% include 'base.html' %}
{% include 'navb.html' %}
{% include 'staffdash.html' %} 
{% block body %}
<div class="container mt-5">
<form class="col-6 mx-auto card p-3" action="" method="post">
    {%csrf_token%}
    <h5>Are you sure to update this status?</h5><br>
    <label for="id_status">Update status</label>
    <select class="form-control " name="status" required="" id="id_status">
      <option value="" selected="">{{regcomplaints.status}}</option>
                                  
      <option value="Pending">Pending</option>
                                  
      <option value="InProgress">In Progress</option>
                                  
      <option value="Solved">Solved</option>
                                  
      </select><br>
      <td><button type="submit" class="btn btn-danger">Update</button></td>
      <!-- <input type='hidden' name="id" value={{grieve.id}}> -->
    </form>
</div>
{% endblock %}<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}
<style>

    .container{
      text-align: center;
    }
    </style>